
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-6
pull_requests: [{"author":{"id":"U_kgDOB740jQ","is_bot":false,"login":"sawyerrice","name":""},"headRefName":"Sawyer-MenuItemForm","number":186,"title":"Sawyer menu item form","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/186"},{"author":{"id":"MDQ6VXNlcjg5NTU1MzQw","is_bot":false,"login":"nbelle1","name":"Nik Belle"},"headRefName":"Nik-Organization","number":184,"title":"Organization Fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/184"},{"author":{"id":"U_kgDOB740jQ","is_bot":false,"login":"sawyerrice","name":""},"headRefName":"Sawyer-MenuFixtures","number":183,"title":"Sawyer menu fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/183"},{"author":{"id":"U_kgDOB740jQ","is_bot":false,"login":"sawyerrice","name":""},"headRefName":"Sawyer-UCSBMenuItem","number":182,"title":"SR- adding menu item team02 files","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/182"}]
