
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-6
pull_requests: [{"author":{"id":"U_kgDOBXuvwQ","is_bot":false,"login":"brycewangg","name":"Bryce Wang"},"headRefName":"Bryce-H05","number":238,"title":"Bryce H05 MenuItemReview Integration Test","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/238"},{"author":{"id":"U_kgDOB740jQ","is_bot":false,"login":"sawyerrice","name":""},"headRefName":"Sawyer-HW05","number":237,"title":"Sawyer E2E and Integration Tests HW05, DO NOT MERGE","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/237"},{"author":{"id":"MDQ6VXNlcjI0NzgzNDE3","is_bot":false,"login":"dakotazoid56","name":"Dakota"},"headRefName":"Dakota-H05","number":236,"title":"DONT MERGE!!!!!  ( -- Dakota H05 -- )","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/236"},{"author":{"id":"MDQ6VXNlcjg5NTU1MzQw","is_bot":false,"login":"nbelle1","name":"Nik Belle"},"headRefName":"Nik-H05","number":234,"title":"Nik H05 Integration and E2E Testing (DO NOT MERGE)","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/234"},{"author":{"id":"U_kgDOCeKwaw","is_bot":false,"login":"ok-at-computers","name":"Kevin"},"headRefName":"Kevin-Articles-H05","number":230,"title":"Kevin Articles h05 integration tests (DO NOT MERGE)","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/230"}]
