
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-6
pull_requests: [{"author":{"id":"U_kgDOBXuvwQ","is_bot":false,"login":"brycewangg","name":"Bryce Wang"},"headRefName":"Bryce-MenuItemReview-Form","number":216,"title":"Add Form for MenuItemReview","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/216"},{"author":{"id":"U_kgDOBXuvjg","is_bot":false,"login":"emanbareket","name":""},"headRefName":"Immanuel-Help","number":215,"title":"fixtures","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/215"},{"author":{"id":"MDQ6VXNlcjg5NTU1MzQw","is_bot":false,"login":"nbelle1","name":"Nik Belle"},"headRefName":"Nik-Organization-Placeholders","number":214,"title":"Organization placeholders for pages and add to app and nav ","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/214"},{"author":{"id":"MDQ6VXNlcjg5NTU1MzQw","is_bot":false,"login":"nbelle1","name":"Nik Belle"},"headRefName":"Nik-Organization-Form","number":213,"title":"Organization table and tests","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/213"}]
