
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team03-s24-4pm-6
owner: ucsb-cs156-s24
repo_name: team03-s24-4pm-6
pull_requests: [{"author":{"id":"MDQ6VXNlcjI0NzgzNDE3","is_bot":false,"login":"dakotazoid56","name":"Dakota"},"headRefName":"Dakota-RecRequest-BuxFix","number":233,"title":"Dakota - Rec Request Bug Fix","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/233"},{"author":{"id":"U_kgDOCeKwaw","is_bot":false,"login":"ok-at-computers","name":"Kevin"},"headRefName":"Kevin-Articles-H05","number":230,"title":"Kevin Articles h05 integration tests (DO NOT MERGE)","url":"https://github.com/ucsb-cs156-s24/team03-s24-4pm-6/pull/230"}]
